apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  params:
    - name: NAME
      type: string
    - name: NAMESPACE
      type: string
  steps:
    - name: deploy
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/usr/bin/env bash

        oc rollout status dc/$(params.NAME) -n $(params.NAMESPACE)
