spec:
  template:
    spec:
      containers:
        - env:
            - name: JAVA_DEBUG
              value: "true"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: '1'
              memory: 1Gi