spec:
  replicas: 1
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - summit-lab-spring-music
          - spring-boot
        from:
          kind: ImageStreamTag
          name: summit-lab-spring-music:1.0
  template:
    spec:
      containers:
        - env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: summit-lab-spring-music-db
                  key: database-name
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: summit-lab-spring-music-db
                  key: database-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: summit-lab-spring-music-db
                  key: database-password
            - name: SPRING_DATASOURCE_URL
              value: 'jdbc:postgresql://summit-lab-spring-music-db/$(DB_NAME)'
