metadata:
  labels:
    app.openshift.io/runtime: spring
    app.kubernetes.io/part-of: spring-music
spec:
  template:
    spec:
      containers:
        - env:
            - name: JAVA_DEBUG
              value: "true"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: '1'
              memory: 1Gi
