spring:
  application:
    name: summit-lab-spring-music
  main:
    allow-bean-definition-overriding: true
  jpa:
    generate-ddl: true
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full

logging:
  level:
    root: WARN
    io.k8s.samples.music: DEBUG


