spring:
  application:
    name: spring-music
  main:
    allow-bean-definition-overriding: true
  jpa:
    generate-ddl: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full

logging:
  level:
    root: WARN
    io.k8s.samples.music: DEBUG

---
spring:
  profiles: '!redis'

management:
  health:
    redis:
      enabled: false
---
spring:
  profiles: '!mongodb'

management:
  health:
    mongo:
      enabled: false
---
spring:
  profiles: mysql
  datasource:
    url: "jdbc:mysql://localhost/music"
    username:
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
---
spring:
  profiles: postgres
  datasource:
    url: "jdbc:postgresql://localhost/music"
    username: postgres
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.ProgressDialect
