apiVersion: v1
kind: Template
metadata:
  name: summit-lab-spring-music-db
parameters:
  - name: DATABASE_NAME
    value: music
    description: The name of the database to use
    required: true
  - name: DATABASE_USERNAME
    generate: expression
    from: "[a-zA-Z]{32}"
    description: The database username
  - name: DATABASE_PASSWORD
    generate: expression
    from: "[a-zA-Z0-9]{32}"
    description: The database password
  - name: DATABASE_ADMIN_PASSWORD
    generate: expression
    from: "[a-zA-Z0-9]{32}"
    description: The database admin password
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: summit-lab-spring-music-db
      labels:
        application: summit-lab-spring-music
      annotations:
        template.openshift.io/expose-database_name: '{.data[''database-name'']}'
        template.openshift.io/expose-password: '{.data[''database-password'']}'
        template.openshift.io/expose-username: '{.data[''database-user'']}'
        template.openshift.io/expose-admin_password: '{.data["database-admin-password"]}'
    stringData:
      database-name: ${DATABASE_NAME}
      database-password: ${DATABASE_PASSWORD}
      database-user: ${DATABASE_USERNAME}
      database-admin-password: ${DATABASE_ADMIN_PASSWORD}
  - kind: Secret
    apiVersion: v1
    metadata:
      name: summit-lab-spring-music-db-connector-creds
      labels:
        app: spring-music-cdc
    type: Opaque
    stringData:
      connector.properties: |-
        dbUsername: ${DATABASE_USERNAME}
        dbPassword: ${DATABASE_PASSWORD}
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: summit-lab-spring-music-db
      labels:
        application: summit-lab-spring-music
        app: spring-music
        app.kubernetes.io/part-of: spring-music
        app.openshift.io/runtime: mysql
      annotations:
        template.alpha.openshift.io/wait-for-ready: "true"
    spec:
      replicas: 1
      strategy:
        type: Recreate
      selector:
        name: summit-lab-spring-music-db
      template:
        metadata:
          name: summit-lab-spring-music-db
          labels:
            name: summit-lab-spring-music-db
        spec:
#          strategy:
#            rollingParams:
#              post:
#                execNewPod:
#                  command:
#                    - /bin/sh
#                    - -c
#                    -
          volumes:
            - name: db-data
              emptyDir: {}
          containers:
            - env:
                - name: MYSQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: summit-lab-spring-music-db
                      key: database-user
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: summit-lab-spring-music-db
                      key: database-password
                - name: MYSQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: summit-lab-spring-music-db
                      key: database-name
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: summit-lab-spring-music-db
                      key: database-admin-password
              name: summit-lab-spring-music-db
              image: registry.redhat.io/rhel8/mysql-80:latest
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: db-data
                  mountPath: /var/lib/mysql/data
              ports:
#                - containerPort: 5432
                - containerPort: 3306
                  protocol: TCP
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 3306
#                exec:
#                  command:
#                    - /bin/sh
#                    - -i
#                    - -c
#                    - mysqladmin -u$MYSQL_USER -p$MYSQL_PASSWORD -h 127.0.0.1 ping
##                    - pg_isready -h 127.0.0.1 -p 5432
                timeoutSeconds: 1
              readinessProbe:
                exec:
                  command:
                    - /bin/sh
                    - -i
                    - -c
                    - >-
                      MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER
                      -D $MYSQL_DATABASE -e 'SELECT 1'
#                    - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c 'SELECT 1'
                failureThreshold: 3
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  memory: 512Mi
              securityContext:
                privileged: false
      triggers:
        - type: ConfigChange
        # - type: ImageChange
        #   imageChangeParams:
        #     automatic: true
        #     containerNames:
        #       - summit-lab-spring-music-db
        #     from:
        #       kind: ImageStreamTag
        #       name: postgresql-12:latest
        #       namespace: openshift
  - kind: Service
    apiVersion: v1
    metadata:
      name: summit-lab-spring-music-db
      labels:
        application: summit-lab-spring-music
    spec:
      ports:
        - name: mysql
          port: 3306
          protocol: TCP
          targetPort: 3306
#        - name: postgres
#          port: 5432
#          protocol: TCP
#          targetPort: 5432
      selector:
        name: summit-lab-spring-music-db
