apiVersion: v1
kind: Template
metadata:
  name: spring-music-mongodb
  annotations:
    iconClass: icon-spring
    description: Application template for deploying the spring-music application on OpenShift using a MongoDB backend
parameters:
  - name: SPRING_PROFILES_ACTIVE
    value: mongodb
    description: The profiles to activate in the spring context
    required: true
  - name: APPLICATION_NAME
    value: spring-music
    description: The application name
    required: true
  - name: DATABASE_NAME
    value: music
    description: The name of the database to use
    required: true
  - name: DATABASE_USERNAME
    generate: expression
    from: "[a-zA-Z]{32}"
    description: The database username
  - name: DATABASE_PASSWORD
    generate: expression
    from: "[a-zA-Z0-9]{32}"
    description: The database password
  - name: DATABASE_ADMIN_PASSWORD
    generate: expression
    from: "[a-zA-Z0-9]{32}"
    description: The database admin password
  - name: GITHUB_TRIGGER_SECRET
    generate: expression
    from: '[a-zA-Z0-9]{8}'
    description: GitHub trigger secret
  - name: GENERIC_TRIGGER_SECRET
    generate: expression
    from: '[a-zA-Z0-9]{8}'
    description: Generic build trigger secret
labels:
  createdBy: spring-music-mongodb-template
  template: spring-music-mongodb
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${APPLICATION_NAME}-db
      labels:
        application: ${APPLICATION_NAME}
      annotations:
        template.openshift.io/expose-database_name: '{.data[''database-name'']}'
        template.openshift.io/expose-password: '{.data[''database-password'']}'
        template.openshift.io/expose-username: '{.data[''database-user'']}'
        template.openshift.io/expose-admin_password: '{.data["database-admin-password"]}'
    stringData:
      database-name: ${DATABASE_NAME}
      database-password: ${DATABASE_PASSWORD}
      database-user: ${DATABASE_USERNAME}
      database-admin-password: ${DATABASE_ADMIN_PASSWORD}
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APPLICATION_NAME}-config
      labels:
        application: ${APPLICATION_NAME}
    data:
      spring.data.mongodb.uri: 'mongodb://${APPLICATION_NAME}-db:27017/${DATABASE_NAME}'
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: s2i-java
      labels:
        application: ${APPLICATION_NAME}
    spec:
      tags:
        - annotations:
            openshift.io/imported-from: fabric8/s2i-java
          from:
            kind: DockerImage
            name: fabric8/s2i-java
          name: 3.0.0-java11
          referencePolicy:
            type: Source
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        application: ${APPLICATION_NAME}
    spec:
      tags:
        - name: latest
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        application: ${APPLICATION_NAME}
    spec:
      triggers:
        - type: Generic
          generic:
            secret: ${GENERIC_TRIGGER_SECRET}
        - type: GitHub
          github:
            secret: ${GITHUB_TRIGGER_SECRET}
        - type: ConfigChange
        - type: ImageChange
      source:
        type: Git
        git:
          ref: k8s
          uri: https://github.com/edeandrea/spring-music.git
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: s2i-java:3.0.0-java11
      output:
        to:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${APPLICATION_NAME}-db
      labels:
        template: mongodb-ephemeral-template
        application: ${APPLICATION_NAME}
      annotations:
        template.alpha.openshift.io/wait-for-ready: "true"
    spec:
      replicas: 1
      strategy:
        type: Recreate
      selector:
        name: ${APPLICATION_NAME}-db
      template:
        metadata:
          name: ${APPLICATION_NAME}-db
          labels:
            name: ${APPLICATION_NAME}-db
        spec:
          containers:
            - env:
                - name: MONGODB_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${APPLICATION_NAME}-db
                      key: database-user
                - name: MONGODB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${APPLICATION_NAME}-db
                      key: database-password
                - name: MONGODB_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: ${APPLICATION_NAME}-db
                      key: database-name
                - name: MONGODB_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${APPLICATION_NAME}-db
                      key: database-admin-password
              name: ${APPLICATION_NAME}-db
              image: rhscl/mongodb-34-rhel7
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 27017
                  protocol: TCP
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 27017
                timeoutSeconds: 1
              readinessProbe:
                exec:
                  command:
                    - /bin/sh
                    - -i
                    - -c
                    - mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD --eval="quit()"
                failureThreshold: 3
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  memory: 512Mi
              securityContext:
                privileged: false
              volumeMounts:
                - mountPath: /var/lib/mongodb/data
                  name: ${APPLICATION_NAME}-db-data
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${APPLICATION_NAME}-db
            from:
              kind: ImageStreamTag
              name: mongodb:3.4
              namespace: openshift
        - type: ConfigChange
      volumes:
        - name: ${APPLICATION_NAME}-db-data
          emptyDir: {}
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${APPLICATION_NAME}-db
      labels:
        template: mongodb-ephemeral-template
        application: ${APPLICATION_NAME}
    spec:
      ports:
        - name: mongodb
          port: 27017
          protocol: TCP
          targetPort: 27017
      selector:
        name: ${APPLICATION_NAME}-db
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        deploymentconfig: ${APPLICATION_NAME}
        application: ${APPLICATION_NAME}
    spec:
      replicas: 1
      selector:
        application: ${APPLICATION_NAME}
        deploymentconfig: ${APPLICATION_NAME}
      strategy:
        type: Recreate
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${APPLICATION_NAME}
            from:
              kind: ImageStreamTag
              name: ${APPLICATION_NAME}:latest
      template:
        metadata:
          labels:
            deploymentconfig: ${APPLICATION_NAME}
            application: ${APPLICATION_NAME}
        spec:
          containers:
            - name: ${APPLICATION_NAME}
              image: ${APPLICATION_NAME}
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: ${SPRING_PROFILES_ACTIVE}
                - name: SPRING_DATA_MONGODB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: ${APPLICATION_NAME}-db
                      key: database-user
                - name: SPRING_DATA_MONGODB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${APPLICATION_NAME}-db
                      key: database-password
                - name: SPRING_DATA_MONGODB_URI
                  valueFrom:
                    configMapKeyRef:
                      name: ${APPLICATION_NAME}-config
                      key: spring.data.mongodb.uri
              resources:
                requests:
                  memory: 512Mi
                  cpu: 100m
                limits:
                  memory: 1Gi
                  cpu: 500m
              readinessProbe:
                timeoutSeconds: 3
                initialDelaySeconds: 5
                httpGet:
                  path: /actuator/health
                  port: 8080
              livenessProbe:
                timeoutSeconds: 3
                initialDelaySeconds: 30
                httpGet:
                  path: /actuator/health
                  port: 8080
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        application: ${APPLICATION_NAME}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
        - name: 8778-tcp
          port: 8778
          protocol: TCP
          targetPort: 8778
        - name: 9779-tcp
          port: 9779
          protocol: TCP
          targetPort: 9779
      selector:
        deploymentconfig: ${APPLICATION_NAME}
  - kind: Route
    apiVersion: v1
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        application: ${APPLICATION_NAME}
      annotations:
        description: Route for the applications http service
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: ${APPLICATION_NAME}
